name: options_file
version: 1.0.0
author: James Ots <code@jamesots.com>
description: Read options files
homepage: https://github.com/jamesots/optionsfile

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.8
